### ISSUE TITLE
NameError exceptions

### ISSUE THREAD

**Issue by Quorth** [patois/NECromancer#1]
Hello,
I am having some trouble using the plugin. Here is a description of the issue, and a quick fix to it.

This is the output after loading the binary in IDA Pro 7:
```
  bytes   pages size description
--------- ----- ---- --------------------------------------------
  3063808   374 8192 allocating memory for b-tree...
  3063808   374 8192 allocating memory for virtual array...
   262144    32 8192 allocating memory for name pointers...
-----------------------------------------------------------------
  6389760            total memory allocated

Loading processor module C:\Program Files\IDA 7.0\procs\nec850.dll for V850E1...OK
Autoanalysis subsystem has been initialized.
NECromancer intialized.
Analysis options are reset to the configuration file defaults
Loading file XXX into database...
Detected file format: Binary file
  0. Creating a new segment  (00000000-000BB3A4) ... ... OK
Flushing buffers, please wait...ok
File XXX has been successfully loaded into the database.
IDA is analysing the input file...
You may start to explore the input file right now.
```
At this point I define as code the reset vector address, and I get
```
-----------------------------------------------------------------------------------------
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] 
IDAPython v1.7.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
-----------------------------------------------------------------------------------------
The initial autoanalysis has been finished.
```
Followed by several exceptions like this:
```
Exception in IDP Hook function: SWIG director method error. Error detected when calling 'IDP_Hooks.ev_ana_insn'
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins/NECromancer.py", line 296, in ev_ana_insn
    return self.decode_instruction(insn)
  File "C:/Program Files/IDA 7.0/plugins/NECromancer.py", line 162, in decode_instruction
    insn.Op2.dtyp = dt_dword
NameError: global name 'dt_dword' is not defined
```
and some like this:
```
Exception in IDP Hook function: SWIG director method error. Error detected when calling 'IDP_Hooks.ev_out_mnem'
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins/NECromancer.py", line 302, in ev_out_mnem
    color = COLOR_INSN
NameError: global name 'COLOR_INSN' is not defined
```
I don't know if the issue is because of my IDA Pro config, but I quick-hacked the issue by adding the line `from idaapi import *` at the very beginning of the script.

Hope it helps. Cheers,

Q.

**Comment by patois** [comment]
Thanks for pointing this out. It's (hopefully) fixed with today's commit.
